# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import serial
from time import sleep


ser = serial.Serial(port = "COM6", baudrate = 9600)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(81, 130, 611, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar1 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar1.setProperty("value", 1)
        self.progressBar1.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1.setObjectName("progressBar1")
        self.horizontalLayout.addWidget(self.progressBar1)
        self.progressBar2 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar2.setProperty("value", 1)
        self.progressBar2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar2.setObjectName("progressBar2")
        self.horizontalLayout.addWidget(self.progressBar2)
        self.progressBar3 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar3.setProperty("value", 1)
        self.progressBar3.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar3.setObjectName("progressBar3")
        self.horizontalLayout.addWidget(self.progressBar3)
        self.progressBar4 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar4.setProperty("value", 1)
        self.progressBar4.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar4.setObjectName("progressBar4")
        self.horizontalLayout.addWidget(self.progressBar4)
        self.progressBar5 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar5.setProperty("value", 1)
        self.progressBar5.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar5.setObjectName("progressBar5")
        self.horizontalLayout.addWidget(self.progressBar5)
        self.progressBar6 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar6.setProperty("value", 1)
        self.progressBar6.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar6.setObjectName("progressBar6")
        self.horizontalLayout.addWidget(self.progressBar6)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 350, 551, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout_2.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_2.addWidget(self.checkBox_6)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(141, 90, 541, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clicker())
        self.pushButton.setGeometry(QtCore.QRect(300, 430, 161, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_1.setText(_translate("MainWindow", "1"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_5.setText(_translate("MainWindow", "5"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.label.setText(_translate("MainWindow", "Value 1"))
        self.label_2.setText(_translate("MainWindow", "Value 2"))
        self.label_3.setText(_translate("MainWindow", "Value 3"))
        self.label_4.setText(_translate("MainWindow", "Value 4"))
        self.label_5.setText(_translate("MainWindow", "Value 5"))
        self.label_6.setText(_translate("MainWindow", "Value 6"))
        self.pushButton.setText(_translate("MainWindow", "Confirm"))


    def clicker(self):
    
        arr = [
        self.checkBox_1.isChecked(),
        self.checkBox_2.isChecked(),
        self.checkBox_3.isChecked(),
        self.checkBox_4.isChecked(),
        self.checkBox_5.isChecked(),
        self.checkBox_6.isChecked()
        ]
        
        data_to_send = ''.join(['1' if state else '0' for state in arr]) + '\n'
        
        ser.write(data_to_send.encode("utf-8"))
        ser.flush()
        
        data_recieved = ser.read_until(b"\n").decode("utf-8").strip()
        label_values = data_recieved.split(",")
        
        labels = [self.label, self.label_2, self.label_3, self.label_4, self.label_5, self.label_6]
        progBars = [self.progressBar1, self.progressBar2, self.progressBar3, self.progressBar4, self.progressBar5, self.progressBar6]
        
        for label, val, prog in zip(labels, label_values, progBars): #zip() combines two arrays
            try:
                floatVal = float(val)
                label.setText(f"{floatVal:.2f}") #.2f is for 2 decimals    
                prog.setValue(int(floatVal))
            except ValueError:
                label.setText("Error")
                prog.setValue(0)    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
