# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
from time import sleep

ser = serial.Serial('COM6', 9600)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(290, 300, 250, 100))
        self.label1.setObjectName("label1")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(260, 230, 225, 48))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox1 = QtWidgets.QComboBox(self.widget)
        self.comboBox1.setMaxVisibleItems(8)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox1 = QtWidgets.QSpinBox(self.widget)
        self.spinBox1.setMaximum(5000)
        self.spinBox1.setObjectName("spinBox1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox1)
        self.pushButton1 = QtWidgets.QPushButton(self.splitter, clicked = lambda: self.clicker() )
        self.pushButton1.setObjectName("pushButton1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def clicker(self):
        #ser.write(self.comboBox1.currentText().encode())
        
        #while ser.in_waiting:
        #    read_data = ser.readline().decode()
        
        self.label1.setText(f'Sending column {self.comboBox1.currentText()} with a delay of {self.spinBox1.cleanText()}ms  \nRecieved:')
        sleep(int(self.spinBox1.cleanText())/1000)

        




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Waiting.."))
        self.label_2.setText(_translate("MainWindow", "Column to read"))
        self.comboBox1.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox1.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox1.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox1.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox1.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox1.setItemText(7, _translate("MainWindow", "8"))
        self.label.setText(_translate("MainWindow", "Delay(ms)"))
        self.pushButton1.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
