# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Blink.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import rw

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.interval = QtWidgets.QComboBox(Dialog)
        self.interval.setGeometry(QtCore.QRect(30, 90, 80, 24))
        self.interval.setObjectName("interval")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.count = QtWidgets.QComboBox(Dialog)
        self.count.setGeometry(QtCore.QRect(250, 90, 80, 24))
        self.count.setObjectName("count")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(240, 30, 104, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 104, 31))
        self.textEdit.setObjectName("textEdit")
        
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.display) #prints out the data
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def display(self):
      ##  print(f"{self.interval.currentText()} interval\n")
      ##  print(f"{self.count.currentText()} count")
        interval = self.interval.currentText()
        count = self.count.currentText()
        rw.Data(interval, count)
    
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.interval.setItemText(0, _translate("Dialog", "250"))
        self.interval.setItemText(1, _translate("Dialog", "500"))
        self.interval.setItemText(2, _translate("Dialog", "750"))
        self.interval.setItemText(3, _translate("Dialog", "1000"))
        self.interval.setItemText(4, _translate("Dialog", "1250"))
        self.interval.setItemText(5, _translate("Dialog", "1500"))
        self.interval.setItemText(6, _translate("Dialog", "1750"))
        self.interval.setItemText(7, _translate("Dialog", "2000"))
        self.interval.setItemText(8, _translate("Dialog", "2250"))
        self.interval.setItemText(9, _translate("Dialog", "2500"))
        self.count.setItemText(0, _translate("Dialog", "5"))
        self.count.setItemText(1, _translate("Dialog", "10"))
        self.count.setItemText(2, _translate("Dialog", "15"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Blink Count</p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Blink Interval</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
